apiVersion: apps/v1
kind: Deployment
metadata:
  name: movimentacao-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movimentacao-postgres
  template:
    metadata:
      labels:
        app: movimentacao-postgres
    spec:
      containers:
        - name: movimentacao-postgres
          image: postgres
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-secret
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgresdata
      volumes:
        - name: postgresdata
          persistentVolumeClaim:
            claimName: postgres-volume-claim