version: '3.4'

services:
  rabbit:
    container_name: rabbit.mq
    restart: always
    image: rabbitmq:management
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - benefit-compose-network
      
  mongo:
    container_name: mongo.db
    restart: always
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=Benefit
    networks:
      - benefit-compose-network

  mongoexpress:
    container_name: mongo.express
    restart: always
    image: mongo-express
    ports:
      - 8081:8081
    depends_on:
      - mongo
    environment:
      - ME_CONFIG_MONGODB_URL=mongodb://mongo:27017/
    networks:
      - benefit-compose-network
     
  benefit.api:
    restart: always  
    container_name: benefit.api
    image: ${DOCKER_REGISTRY-}benefitapi
    ports:
      - "8001:80"
    build:
      context: .
      dockerfile: Benefit.API/Dockerfile
    depends_on:
      - mongo
      - rabbit
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - RABBIT_MQ=amqp://guest:guest@rabbit:5672
      - MONGODB_URL=mongodb://mongo:27017/
      - MONGODB_DATABASE=Benefit
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    networks:
      - benefit-compose-network
      
  benefit.consumer.worker:
    container_name: benefit.consumer.worker
    image: ${DOCKER_REGISTRY-}benefitconsumerworker
    build:
      context: .
      dockerfile: Benefit.Consumer.Worker/Dockerfile
    depends_on:
      - mongo
      - rabbit
    environment:
      - RABBIT_MQ=amqp://guest:guest@rabbit:5672
      - MONGODB_URL=mongodb://mongo:27017/
      - MONGODB_DATABASE=Benefit
    networks:
      - benefit-compose-network

networks:
  benefit-compose-network:
    driver: bridge