version: '3.4'

services:
  rabbit:
    container_name: rabbit.mq
    restart: always
    image: rabbitmq:management
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - benefit-compose-network

  postgres:
    container_name: postgres.db
    restart: always
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=guest      
      - POSTGRES_PASSWORD=guest
      - POSTGRES_DB=Benefit
    networks:
      - benefit-compose-network
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  jaeger:
    container_name: jaeger.log  
    image: jaegertracing/all-in-one:latest
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14250:14250"
      - "14268:14268"
      - "14269:14269"
      - "9411:9411"
    networks:
      - benefit-compose-network      

  pgadmin:
    container_name: postgres.admin
    restart: always  
    image: dpage/pgadmin4
    ports:
      - "8002:80"
    depends_on:
      - postgres
    environment:
      - PGADMIN_DEFAULT_EMAIL=guest@guest.com
      - PGADMIN_DEFAULT_PASSWORD=guest
    networks:
      - benefit-compose-network
    volumes:
      - postgres_admin_data:/root/.pgadmin
     
  benefit.api:
    restart: always  
    container_name: benefit.api
    image: ${DOCKER_REGISTRY-}benefitapi
    ports:
      - "8001:80"
    build:
      context: .  
      dockerfile: Benefit.API/Dockerfile
    depends_on:
      - rabbit
      - jaeger
      - postgres
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - RABBIT_MQ=amqp://guest:guest@rabbit:5672
      - DATABASE_TYPE=Postgres
      - DATABASE_CONNECTION=Host=postgres;Database=Benefit;Port=5432;Username=guest;Password=guest
      - JAEGER_AGENT_HOST=jaeger
      - JAEGER_AGENT_PORT=6831
      - JAEGER_SAMPLER_TYPE=remote
      - JAEGER_SAMPLING_ENDPOINT=http://jaeger:5778/sampling
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    networks:
      - benefit-compose-network
      
  benefit.consumer.worker:
    container_name: benefit.consumer.worker
    image: ${DOCKER_REGISTRY-}benefitconsumerworker
    build:
      context: .
      dockerfile: Benefit.Consumer.Worker/Dockerfile
    depends_on:
      - rabbit
      - jaeger      
      - postgres
    environment:
      - RABBIT_MQ=amqp://guest:guest@rabbit:5672
      - DATABASE_TYPE=Postgres
      - DATABASE_CONNECTION=Host=postgres;Database=Benefit;Port=5432;Username=guest;Password=guest
      - JAEGER_AGENT_HOST=jaeger
      - JAEGER_AGENT_PORT=6831
      - JAEGER_SAMPLER_TYPE=remote
      - JAEGER_SAMPLING_ENDPOINT=http://jaeger:5778/sampling      
    networks:
      - benefit-compose-network

volumes:
  postgres_data:
  postgres_admin_data:

networks:
  benefit-compose-network:
    driver: bridge