name: Build-Tests-Toolkit

on:
  push:
    branches: [ main, add-code-covering ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    branches: [ main, add-code-covering ]

env:
  TESTS_PROJECT_PATH: ./src/Toolkit.Test
  PROJECT_PATH: ./src/Toolkit.Test/Toolkit.Test.csproj

jobs:
  Build-Test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['6.0.x']

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET 6
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
        
    - name: Restore Dependencies
      run: dotnet restore ${{ env.PROJECT_PATH }}
      
    - name: Build
      run: dotnet build ${{ env.PROJECT_PATH }} --no-restore

    - name: MSTest+Coverlet
      run: dotnet test ${{ env.PROJECT_PATH }} --logger:"html;LogFileName=resultado-testes.html" --collect:"XPlat Code Coverage"

    - name: Install ReportGenerator
      if: always()
      run: dotnet tool install --global dotnet-reportgenerator-globaltool --version 4.8.4
    
    - name: Generate cover tests reports with ReportGenerator
      if: success()
      run: |
        cd ${{ env.CAMINHO_PROJETO_TESTES }}/TestResults
        cd $(ls -d */|head -n 1)
        reportgenerator "-reports:coverage.cobertura.xml" "-targetdir:coveragereport" -reporttypes:Html 

    - name: Upload UnitTest and Cover Reports as Artifacts
      uses: actions/upload-artifact@v2.2.2
      env:
        TESTS_PROJECT_PATH: ${{ env.TESTS_PROJECT_PATH }}/TestResults/
      if: always()
      with:
        name: resultado-testes
        path: ${{ env.TESTS_PROJECT_PATH }}
        retention-days: 30